branches:
   only:
      - deploy

notifications:
   email:
      on_success: change
      on_failure: always

language: node_js
node_js:
   - "4.1"

before_install:
   - openssl aes-256-cbc -K $encrypted_b9fecb801bae_key -iv $encrypted_b9fecb801bae_iv -in ci/keys.tar.enc -out ci/keys.tar -d
   
install:
   - cd pageroot
   - npm install -g gulp bower
   - npm install
   - bower install

script:
   - gulp
   
after_success:
   - cd ../ci
   - chmod +x deploy.sh
   - ./deploy.sh
   - ssh -i id_rsa -oStrictHostKeyChecking=no kib@konfliktspeliborlange.se "/bin/sh post-deploy.sh"